### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by heriprastiio** [Tanibox/cannia#1]
Failed to compile
./src/App.scss (./node_modules/css-loader??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/sass-loader/lib/loader.js??ref--6-oneOf-5-3!./src/App.scss)
@import "~bootstrap/scss/bootstrap";
^
      File to import not found or unreadable: ~bootstrap/scss/bootstrap.
      in C:\Users\UserWindows\Documents\cannia\src\App.scss (line 1, column 1)

**Comment by bepitulaz** [comment]
@heriprastiio I think there's some configuration that's not working anymore. This project is not updated for months. Perhaps you can send a PR to make it work?

**Comment by heriprastiio** [comment]
Must install the following components: npm i bootstrap-sass, run in the terminal project directory.

Then change line 1, in the C:\Users\UserWindows\Documents\cannia\src\App.scss folder directory (line 1, column 1).

Being @import "../node_modules/bootstrap-scss/bootstrap.scss";
